/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BloodBank } from "./BloodBank";
export * as factories from "./factories";
export { BloodBank__factory } from "./factories/BloodBank__factory";
